---
- hosts: all
  become: yes
  vars:
    page_title: My Landing Page
    page_description: This is my landing page description.
  tasks:
    - name: Install Nginx
      yum:
        name: nginx
        state: latest

    - name: Enable amazon-linux-extras packages
      shell: "amazon-linux-extras enable nginx1"

    
     
    - name: Apply Page Template
      template:
        src: files/landing-page.html.j2
        dest: /usr/share/nginx/html/landing-page.html

    